funny_phrases:
  - "Bravo... {} ! Tu es le héros du jour!"
  - "Félicitations, {} ! Tu es le grand gagnant !"
  - "Chapeau bas, {} ! Tu as été tiré au sort !"
  - "Hourra pour {} ! C’est ton jour de chance !"
  - "Youpi, {} ! Tu es notre super star !"
