members:
- active: false
  name: William
- active: true
  name: Lucien
- active: true
  name: Jean-Marc
- active: false
  name: Anthony
- active: true
  name: Nahuel
- active: true
  name: Adrien
- active: true
  name: Medhy
- active: true
  name: Ludovic
- active: true
  name: "J\xE9r\xF4me"
- active: true
  name: Lucas
- active: false
  name: Maxime
- active: true
  name: Koffi
- active: true
  name: Matthieu
- active: true
  name: Pierre
- active: true
  name: Ugo
- active: true
  name: Roman
