wrap_phrases:
- "Bravo... {} ! Tu es le h\xE9ros du jour!"
- "F\xE9licitations, {} ! Tu es le grand gagnant !"
- "Chapeau bas, {} ! Tu as \xE9t\xE9 tir\xE9 au sort !"
- "Hourra pour {} ! C\u2019est ton jour de chance !"
- Youpi, {} ! Tu es notre super star !
- C'est pas faux, {} ! Tu es notre chevalier du jour !
- En avant, {} ! La table ronde t'acclame !
- "Par la gr\xE2ce d'Excalibur, {} ! Tu es couronn\xE9(e) champion(ne) !"
- "Merlin l'aurait pr\xE9dit, {} ! Tu es l'\xE9lu(e) du jour !"
- "Par Saint Georges, {} ! Ta bravoure est r\xE9compens\xE9e !"
- "Dans les Annales de Bretagne, {} ! Ton nom sera grav\xE9 !"
- "Pour la gloire de Camelot, {} ! Tu es notre conqu\xE9rant(e) !"
- "Par tous les dieux, {} ! Tu es digne des plus grandes l\xE9gendes !"
- "Comme le Roi Arthur, {} ! Ta qu\xEAte est couronn\xE9e de succ\xE8s !"
- "Quelle \xE9pop\xE9e, {} ! Tu es notre preux chevalier !"
- "En avant la garde, {} ! Tu es notre h\xE9ros/h\xE9ro\xEFne du jour !"
- "Dans l\u2019esprit d\u2019un vrai h\xE9ros, {} ! Tu as brillamment triomph\xE9\
  \ !"
- "C\u2019est toi l\u2019\xE9lu(e), {} ! Ton destin est accompli !"
- "Comme Perceval le disait, {} ! C\u2019est la classe !"
- "\xC0 la sauce du Graal, {} ! Tu es le champion ind\xE9tr\xF4nable !"
- "Faites sonner les trompettes, {} ! Ton triomphe est \xE9clatant !"
- Tous les bardes chanteront ton exploit, {} !
- "Tu as bris\xE9 l\u2019enchantement, {} ! Bravo \xE0 toi !"
- "Quelle aventure, {} ! Ton nom restera dans les m\xE9moires !"
- "Chapeau l\u2019artiste, {} ! Tu es notre \xE9toile brillante !"
