wrap_phrases:
- A toi, {}, le champ est libre.
- "Bienvenue {}, nous t'\xE9coutons."
- '{}, tes mots sont de l''or, et nous aimons nous enrichir.'
- Prends la parole, {}, ta sagesse est attendue.
- "Nous sommes tout ou\xEFe, {}, partage tes pens\xE9es."
- "A toi de jouer, {}, le forum est \xE0 toi."
- "La table ovale t'\xE9coute, {}."
- '{}, tes paroles sont attendues avec impatience.'
- "Exprime-toi, {}, nous sommes captiv\xE9s."
- "C'est \xE0 toi, {}, de nous \xE9blouir par ton discours."
- "La sc\xE8ne est \xE0 toi, {}, \xE9claire-nous de ta lumi\xE8re."
- "Partage ton savoir, {}, nous sommes pr\xEAts \xE0 apprendre."
- "\xC0 toi l'honneur, {}, de nous inspirer."
- "Nous te laissons la parole, {}, \xE9merveille-nous."
- "\xC0 toi de nous enchanter, {}."
- "C'est ton moment, {}, fais-nous r\xEAver."
- "Nous attendons tes paroles, {}, \xE9claire notre chemin."
- '{}, tu as la parole, et nous avons l''oreille.'
- "Nous sommes pr\xEAts \xE0 t'\xE9couter, {}, guide-nous par tes mots."
- "C'est \xE0 toi, {}, de nous guider par ta sagesse."
